branches:
  only:
    - master
    - develop

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx
      osx_image: xcode8

before_install:
  - git submodule update --init --remote --merge --recursive
  - git clone -b master https://$GITHUB_USER:$GITHUB_PWD@github.com/IBM-Swift/BluePic-Testing-Credentials.git

script:
  - cd BluePic-Server && ./Package-Builder/build-package.sh $TRAVIS_BRANCH $TRAVIS_BUILD_DIR $TRAVIS_BUILD_DIR/BluePic-Testing-Credentials/development
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then cd $TRAVIS_BUILD_DIR/BluePic-iOS; xcodebuild -workspace BluePic.xcworkspace/ -scheme BluePic -sdk iphonesimulator10.0 ONLY_ACTIVE_ARCH=NO; fi
