# To use this file, simply execute: docker-compose up
# make sure you have filled out the credentials in the cloud.json file before running this
app:
  image: ibmcom/swift-ubuntu
  ports:
    - "8090:8090"
  volumes:
    - .:/root/BluePic
  command: bash -c "cd /root/BluePic && rm -rf Packages && swift build --clean && swift build && ./.build/debug/BluePicServer"
